### PR TITLE
fixed for perl 5.22 on Windows

### PR DESCRIPTION
**Pull request by chorny**

### CODE REVIEW

**Comment by mquinson** [comment]
It seems to be not entierely sufficient, at least for me: https://ci.appveyor.com/project/mquinson/simgrid/build/931
My copy of IPC::Run should be uptodate with the one in this repository: https://github.com/mquinson/simgrid/tree/master/tools/cmake/scripts/IPC
I am using it for a test runner, which code is here: https://github.com/mquinson/simgrid/blob/master/tools/tesh/tesh.pl

**Comment by mquinson** [comment]
I forgot: many thanks for considering the issue #16, as I am really unable of doing so myself. Your help is really appreciated.

**Comment by chorny** [comment]
> It seems to be not entierely sufficient, at least for me

Part of patch is to require newer Win32API::File.

**Comment by mquinson** [comment]
Yes, my bad. So I take it back. I am somehow unable to test it with a fresh version of Win32API::File right now, so you'd better ignore my comments. Sorry for the noise.

**Pull request merged**
